In [1]:
import seaborn as sns

In [5]:
data = sns.load_dataset('tips')
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
## Average total bill of the customer who is a smoker?

In [10]:
data.shape

(244, 7)

## Filtering the data

In [12]:
data[data['smoker'] == 'Yes']

total_bill   tip     sex smoker  day    time  size
56        38.01  3.00    Male    Yes  Sat  Dinner     4
58        11.24  1.76    Male    Yes  Sat  Dinner     2
60        20.29  3.21    Male    Yes  Sat  Dinner     2
61        13.81  2.00    Male    Yes  Sat  Dinner     2
62        11.02  1.98    Male    Yes  Sat  Dinner     2
..          ...   ...     ...    ...  ...     ...   ...
234       15.53  3.00    Male    Yes  Sat  Dinner     2
236       12.60  1.00    Male    Yes  Sat  Dinner     2
237       32.83  1.17    Male    Yes  Sat  Dinner     2
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[93 rows x 7 columns]

In [15]:
data_yes = data[data['smoker'] == 'Yes']
data_yes

total_bill   tip     sex smoker  day    time  size
56        38.01  3.00    Male    Yes  Sat  Dinner     4
58        11.24  1.76    Male    Yes  Sat  Dinner     2
60        20.29  3.21    Male    Yes  Sat  Dinner     2
61        13.81  2.00    Male    Yes  Sat  Dinner     2
62        11.02  1.98    Male    Yes  Sat  Dinner     2
..          ...   ...     ...    ...  ...     ...   ...
234       15.53  3.00    Male    Yes  Sat  Dinner     2
236       12.60  1.00    Male    Yes  Sat  Dinner     2
237       32.83  1.17    Male    Yes  Sat  Dinner     2
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[93 rows x 7 columns]

In [17]:
data_yes['total_bill'].mean()

20.756344086021507

In [20]:
data[data['smoker'] == 'Yes']['total_bill'].mean()

20.756344086021507

In [22]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
arr[[5,6,7,8]]

array([60, 70, 80, 90])

## Boolean Indexing

In [24]:
arr > 50

array([False, False, False, False, False,  True,  True,  True,  True])

In [25]:
arr[arr > 50]

array([60, 70, 80, 90])

In [26]:
arr1 = np.array([500, 30, 1, 20, 1500, 25, 45, 70])
arr1

array([ 500,   30,    1,   20, 1500,   25,   45,   70])

In [27]:
arr1[arr1 > 50]

array([ 500, 1500,   70])

In [28]:
arr1[1]

30

In [30]:
arr[arr > 50]

array([60, 70, 80, 90])

In [29]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [32]:
data[data['time'] == 'Dinner']

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]

## Check the average bill on higher on weekends or weekdays?

In [33]:
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [41]:
data[(data['day'] == 'Sat') | (data['day'] == 'Sun')]['total_bill'].mean()

20.893006134969326

In [42]:
data[(data['day'] != 'Sat') | (data['day'] != 'Sun')]['total_bill'].mean()

19.78594262295082

# Average total_bill sex wise

In [43]:
data.groupby('sex').mean()

C:\Users\AMANT\AppData\Local\Temp\ipykernel_22512\2488681688.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data.groupby('sex').mean()


total_bill       tip      size
sex                                   
Male     20.744076  3.089618  2.630573
Female   18.056897  2.833448  2.459770

In [44]:
data.groupby('day').mean()

C:\Users\AMANT\AppData\Local\Temp\ipykernel_22512\3958528645.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data.groupby('day').mean()


total_bill       tip      size
day                                 
Thur   17.682742  2.771452  2.451613
Fri    17.151579  2.734737  2.105263
Sat    20.441379  2.993103  2.517241
Sun    21.410000  3.255132  2.842105