In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
data=pd.read_csv('Movie_classification.csv')
data.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [3]:
data.isnull().sum()

Marketing expense       0
Production expense      0
Multiplex coverage      0
Budget                  0
Movie_length            0
Lead_ Actor_Rating      0
Lead_Actress_rating     0
Director_rating         0
Producer_rating         0
Critic_rating           0
Trailer_views           0
3D_available            0
Time_taken             12
Twitter_hastags         0
Genre                   0
Avg_age_actors          0
Num_multiplex           0
Collection              0
Start_Tech_Oscar        0
dtype: int64

In [4]:
data=data.dropna()
data.isnull().sum()

Marketing expense      0
Production expense     0
Multiplex coverage     0
Budget                 0
Movie_length           0
Lead_ Actor_Rating     0
Lead_Actress_rating    0
Director_rating        0
Producer_rating        0
Critic_rating          0
Trailer_views          0
3D_available           0
Time_taken             0
Twitter_hastags        0
Genre                  0
Avg_age_actors         0
Num_multiplex          0
Collection             0
Start_Tech_Oscar       0
dtype: int64

In [5]:
data = pd.get_dummies(data)
data.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Avg_age_actors  Num_multiplex  \
0            7.995           7.94  ...              23            494   
1            7.470           7.44  ...              42            462   
2            7.515           7.44  ...              38            458   
3            7.020           8.26  ...              45            472   
4            7.070           8.26  ...              55            395   

   Collection  Start_Tech_Oscar  3D_available_NO  3D_available_YES  \
0       48000                 1                0                 1   
1       43200                 0                1                 0   
2       69400                 1                1                 0   
3       66800                 1                0                 1   
4       72400                 1                1                 0   

   Genre_Action  Genre_Comedy  Genre_Drama  Genre_Thriller  
0             0             0            0               1  
1             0             0            1               0  
2             0             1            0               0  
3             0             0            1               0  
4             0             0            1               0  

[5 rows x 23 columns]

In [6]:
X=data.drop('Start_Tech_Oscar',axis=1)
y=data['Start_Tech_Oscar']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc

DecisionTreeClassifier()

In [9]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier()

In [10]:
y_pred=dtc.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.5353535353535354

In [12]:
from sklearn.metrics  import confusion_matrix
confusion_matrix(y_pred,y_test)


array([[19, 22],
       [24, 34]], dtype=int64)

In [14]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc

RandomForestClassifier()

In [15]:
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [17]:
y_pred = rfc.predict(X_test)
y_pred

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [18]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred, y_test)

array([[21, 16],
       [22, 40]], dtype=int64)

In [19]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6161616161616161

### The default decision trees considered as a part of Random Forest Algorithm is 50 
To control the number of decision trees we can use the n_estimators parameter as shown below

In [20]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 100)