In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv("Carseats.csv")
data.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [3]:
data.shape

(400, 11)

In [4]:
data.isnull().sum()

Sales          0
CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
dtype: int64

In [5]:
from sklearn.preprocessing import MinMaxScaler
mms= MinMaxScaler()
mms

MinMaxScaler()

In [6]:
data[['Sales','CompPrice','Income','Advertising','Population','Price','Age','Education']]=mms.fit_transform(data[['Sales','CompPrice','Income','Advertising','Population','Price','Age','Education']])
data.head()

Sales  CompPrice    Income  Advertising  Population     Price ShelveLoc  \
0  0.583897   0.622449  0.525253     0.379310    0.533066  0.574850       Bad   
1  0.689613   0.346939  0.272727     0.551724    0.501002  0.353293      Good   
2  0.618316   0.367347  0.141414     0.344828    0.519038  0.335329    Medium   
3  0.454825   0.408163  0.797980     0.137931    0.913828  0.437126    Medium   
4  0.255071   0.653061  0.434343     0.103448    0.661323  0.622754       Bad   

        Age  Education Urban   US  
0  0.309091      0.875   Yes  Yes  
1  0.727273      0.000   Yes  Yes  
2  0.618182      0.250   Yes  Yes  
3  0.545455      0.500   Yes  Yes  
4  0.236364      0.375   Yes   No

In [7]:
dic1={'Yes':1,'No':0}
data[['Urban','US']]=data[['Urban','US']].replace(dic1)
data.head()

Sales  CompPrice    Income  Advertising  Population     Price ShelveLoc  \
0  0.583897   0.622449  0.525253     0.379310    0.533066  0.574850       Bad   
1  0.689613   0.346939  0.272727     0.551724    0.501002  0.353293      Good   
2  0.618316   0.367347  0.141414     0.344828    0.519038  0.335329    Medium   
3  0.454825   0.408163  0.797980     0.137931    0.913828  0.437126    Medium   
4  0.255071   0.653061  0.434343     0.103448    0.661323  0.622754       Bad   

        Age  Education  Urban  US  
0  0.309091      0.875      1   1  
1  0.727273      0.000      1   1  
2  0.618182      0.250      1   1  
3  0.545455      0.500      1   1  
4  0.236364      0.375      1   0

In [8]:
data['ShelveLoc'].unique()

array(['Bad', 'Good', 'Medium'], dtype=object)

In [9]:
dic2={'Bad':0, 'Good':2, 'Medium':1}
data['ShelveLoc']=data['ShelveLoc'].replace(dic2)
data.head()

Sales  CompPrice    Income  Advertising  Population     Price  \
0  0.583897   0.622449  0.525253     0.379310    0.533066  0.574850   
1  0.689613   0.346939  0.272727     0.551724    0.501002  0.353293   
2  0.618316   0.367347  0.141414     0.344828    0.519038  0.335329   
3  0.454825   0.408163  0.797980     0.137931    0.913828  0.437126   
4  0.255071   0.653061  0.434343     0.103448    0.661323  0.622754   

   ShelveLoc       Age  Education  Urban  US  
0          0  0.309091      0.875      1   1  
1          2  0.727273      0.000      1   1  
2          1  0.618182      0.250      1   1  
3          1  0.545455      0.500      1   1  
4          0  0.236364      0.375      1   0

In [10]:
X=data.drop('Sales',axis=1)
y=data['Sales']

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)


In [13]:
from sklearn.svm import SVR
svr=SVR()
svr

SVR()

In [14]:
svr.fit(X_train,y_train)

SVR()

In [15]:
y_pred=svr.predict(X_test)

In [16]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)


0.5528481951468525

In [17]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr

LinearRegression()

In [18]:
lr.fit(X_train, y_train)

LinearRegression()

In [19]:
y_pred = lr.predict(X_test)
y_pred

array([0.47846018, 0.60063079, 0.40523566, 0.13195435, 0.45408451,
       0.45233053, 0.50756639, 0.36802514, 0.30814109, 0.39374033,
       0.44370031, 0.25988709, 0.34074542, 0.8645988 , 0.22190265,
       0.3502676 , 0.72985426, 0.45178801, 0.2700201 , 0.35084775,
       0.38147153, 0.5116164 , 0.58705565, 0.52975128, 0.42390479,
       0.67213415, 0.23953479, 0.3719178 , 0.45418114, 0.37740703,
       0.44410841, 0.71029835, 0.42152754, 0.38032909, 0.28281651,
       0.61402778, 0.37472698, 0.39775218, 0.41738786, 0.55253302,
       0.42485879, 0.53903894, 0.38493093, 0.76402188, 0.36053267,
       0.3441505 , 0.48703051, 0.4563149 , 0.75522248, 0.58670126,
       0.12887659, 0.62493115, 0.81317549, 0.6562526 , 0.17144068,
       0.5282992 , 0.36351355, 0.50120095, 0.50201445, 0.25966365,
       0.43917689, 0.83565232, 0.35670798, 0.2603356 , 0.40599623,
       0.51614314, 0.59938082, 0.5898093 , 0.54562348, 0.63441552,
       0.70100454, 0.54358764, 0.73063052, 0.38151986, 0.54153

In [20]:
r2_score(y_test, y_pred)

0.7974511739828186

In [21]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()
dtr

DecisionTreeRegressor()

In [22]:
dtr.fit(X_train, y_train)

DecisionTreeRegressor()

In [23]:
y_pred = dtr.predict(X_test)

In [24]:
r2_score(y_pred, y_test)

0.4371628317079369

In [25]:
from sklearn.neighbors import KNeighborsRegressor
knr = KNeighborsRegressor()
knr

KNeighborsRegressor()

In [26]:
knr.fit(X_train, y_train)

KNeighborsRegressor()

In [27]:
y_pred = knr.predict(X_test)
y_pred

array([0.71259988, 0.37283344, 0.38119238, 0.20848187, 0.34505224,
       0.50387216, 0.44683467, 0.40799017, 0.37529195, 0.47572219,
       0.5323909 , 0.34960049, 0.3457898 , 0.73804548, 0.34960049,
       0.42987093, 0.37775046, 0.42212661, 0.4201598 , 0.43515673,
       0.48801475, 0.49981561, 0.41954518, 0.59225569, 0.51788568,
       0.41684081, 0.35402581, 0.33325138, 0.49170252, 0.45334972,
       0.49600492, 0.47596804, 0.36570375, 0.43822987, 0.40995698,
       0.43257529, 0.38328211, 0.39200983, 0.39913952, 0.65519361,
       0.46588814, 0.61364474, 0.40995698, 0.72550707, 0.32366318,
       0.50116779, 0.3808236 , 0.34173325, 0.6153657 , 0.67682852,
       0.29035034, 0.55464044, 0.69637369, 0.38967425, 0.35341119,
       0.63429625, 0.28469576, 0.29698832, 0.64376152, 0.3016595 ,
       0.46588814, 0.52366318, 0.36508912, 0.45974186, 0.644622  ,
       0.42421635, 0.43589428, 0.4186847 , 0.56939152, 0.60983405,
       0.69637369, 0.45359557, 0.7218193 , 0.49379226, 0.49207

In [28]:
r2_score(y_pred, y_test)

-0.18022495032339725

In [29]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr

RandomForestRegressor()

In [30]:
rfr.fit(X_train, y_train)

RandomForestRegressor()

In [31]:
rfr.predict(X_test)

array([0.45789183, 0.45766441, 0.41457898, 0.22067609, 0.40764597,
       0.39178857, 0.47549478, 0.35814997, 0.32110018, 0.36534112,
       0.39256915, 0.32230486, 0.3165212 , 0.74917025, 0.25481254,
       0.37618931, 0.73706208, 0.43838967, 0.26786724, 0.34825446,
       0.3952059 , 0.48663798, 0.54866011, 0.54945298, 0.36514444,
       0.46963737, 0.26126613, 0.32714813, 0.41615857, 0.44065765,
       0.4732268 , 0.58264905, 0.52247081, 0.40612784, 0.30831592,
       0.50366318, 0.40515673, 0.37749846, 0.39923171, 0.59574677,
       0.4321512 , 0.54854333, 0.36414259, 0.69127843, 0.35401967,
       0.32077443, 0.45789797, 0.42709896, 0.59224954, 0.53361401,
       0.26631223, 0.56968039, 0.72632452, 0.46819299, 0.28202213,
       0.57452981, 0.34349109, 0.45644745, 0.56271051, 0.24944069,
       0.40078672, 0.77499693, 0.33779348, 0.34440074, 0.48703135,
       0.45910879, 0.51054087, 0.46789183, 0.52071297, 0.43514444,
       0.69571604, 0.49287031, 0.66994468, 0.38079902, 0.45326

In [32]:
r2_score(y_test, rfr.predict(X_test))

0.6827656039233904